export const employees = [
    {
      id: 1,
      name: "Juan Pérez",
      position: "Desarrollador Frontend",
      email: "juan.perez@example.com",
      level: 3,
      project: "Proyecto A",
      companyEntryDate: "2020-05-15",
      timeOnLevel: "2 años",
      activeProject: "Proyecto A",
      activeProjectStartDate: "2023-01-10",
      projectRole: "Desarrollador",
      isProjectLead: false,
      certificates: ["React Avanzado", "Node.js"],
      courses: ["Curso de TypeScript", "Curso de Tailwind CSS"],
    },
    {
      id: 2,
      name: "María López",
      position: "Diseñadora UX/UI",
      email: "maria.lopez@example.com",
      level: 2,
      project: "Proyecto B",
      companyEntryDate: "2018-09-01",
      timeOnLevel: "1 año",
      activeProject: "Proyecto B",
      activeProjectStartDate: "2022-11-20",
      projectRole: "Diseñadora",
      isProjectLead: true,
      certificates: ["Diseño UX/UI", "Figma Avanzado"],
      courses: ["Curso de Accesibilidad", "Curso de Prototipado"],
    },
    {
      id: 3,
      name: "Carlos García",
      position: "Gerente de Proyecto",
      email: "carlos.garcia@example.com",
      level: 1,
      project: "Proyecto A",
      companyEntryDate: "2015-03-10",
      timeOnLevel: "3 años",
      activeProject: "Proyecto A",
      activeProjectStartDate: "2021-06-15",
      projectRole: "Gerente",
      isProjectLead: true,
      certificates: ["Gestión de Proyectos", "Scrum Master"],
      courses: ["Curso de Liderazgo", "Curso de Comunicación Efectiva"],
    },
    {
      id: 4,
      name: "Ana Torres",
      position: "Ingeniera de Software",
      email: "ana.torres@example.com",
      level: 5,
      project: "Proyecto C",
      companyEntryDate: "2021-01-25",
      timeOnLevel: "6 meses",
      activeProject: "Proyecto C",
      activeProjectStartDate: "2023-03-01",
      projectRole: "Ingeniera",
      isProjectLead: false,
      certificates: ["AWS Certified Developer", "Docker Essentials"],
      courses: ["Curso de Kubernetes", "Curso de Microservicios"],
    },
  ];